// src/components/OnlineBar.vue
<template>
  <div class="online-bar">
    <div class="ob-section">
      <span class="ob-label">
        <span class="ob-dot online" />
        Online ({{ online.length }})
      </span>
      <div class="ob-avatars">
        <el-tooltip v-for="s in online" :key="s.id" :content="`${s.name} · ${s.roleType}`" placement="bottom">
          <div class="ob-avatar" :style="{ background: nameColor(s.name) }">
            <img v-if="s.avatar" :src="s.avatar" />
            <span v-else>{{ s.name[0]?.toUpperCase() }}</span>
          </div>
        </el-tooltip>
        <span v-if="!online.length" style="font-size:12px;color:#bbb">No one online</span>
      </div>
    </div>
    <div v-if="offline.length" class="ob-divider" />
    <div v-if="offline.length" class="ob-section">
      <span class="ob-label">
        <span class="ob-dot offline" />
        Offline ({{ offline.length }})
      </span>
      <div class="ob-avatars">
        <el-tooltip v-for="s in offline.slice(0,5)" :key="s.id" :content="s.name" placement="bottom">
          <div class="ob-avatar offline" :style="{ background: '#334155' }">
            <span>{{ s.name[0]?.toUpperCase() }}</span>
          </div>
        </el-tooltip>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref, computed, onMounted, onUnmounted } from 'vue'
import request from '@/utils/request'

const staff = ref([])
const online  = computed(() => staff.value.filter(s => s.isOnline))
const offline = computed(() => staff.value.filter(s => !s.isOnline))

async function refresh() {
  try {
    const res = await request({ url: '/tuka/staff/online' })
    staff.value = res.data || []
  } catch {}
}

const colors = ['#16a34a','#2563eb','#9333ea','#ea580c','#0891b2','#be185d']
function nameColor(name) {
  let h = 0
  for (let i = 0; i < name.length; i++) h = name.charCodeAt(i) + ((h << 5) - h)
  return colors[Math.abs(h) % colors.length]
}

let timer
onMounted(() => { refresh(); timer = setInterval(refresh, 60_000) })
onUnmounted(() => clearInterval(timer))
</script>

// src/components/OnlineBar.tsx
import React, { useEffect, useState, useCallback } from 'react'
import { getOnlineStaff } from '../api/staff'
import type { OnlineStaff } from '../types'
import { useAuth } from '../context/AuthContext'
import './OnlineBar.css'

export default function OnlineBar() {
  const { user } = useAuth()
  const [staff, setStaff] = useState<OnlineStaff[]>([])

  const refresh = useCallback(() => {
    getOnlineStaff().then(setStaff).catch(() => {})
  }, [])

  useEffect(() => {
    refresh()
    const t = setInterval(refresh, 60_000) // refresh every 60s — staff list rarely changes
    return () => clearInterval(t)
  }, [refresh])

  const online  = staff.filter(s => s.isOnline)
  const offline = staff.filter(s => !s.isOnline)

  return (
    <div className="online-bar">
      <div className="ob-section">
        <span className="ob-label">
          <span className="ob-dot online" />
          Online ({online.length})
        </span>
        <div className="ob-avatars">
          {online.map(s => (
            <div key={s.id} className="ob-avatar-wrap" title={`${s.name} · ${s.roleType}`}>
              {s.avatar
                ? <img src={s.avatar} className="ob-avatar" alt={s.name} />
                : <div className="ob-avatar ob-avatar-letter" style={{ background: nameColor(s.name) }}>
                    {s.name[0]?.toUpperCase()}
                  </div>
              }
              <span className="ob-status-dot online" />
            </div>
          ))}
          {online.length === 0 && <span className="ob-none">No one online</span>}
        </div>
      </div>

      {offline.length > 0 && (
        <div className="ob-section ob-offline-section">
          <span className="ob-label">
            <span className="ob-dot offline" />
            Offline ({offline.length})
          </span>
          <div className="ob-avatars">
            {offline.slice(0, 5).map(s => (
              <div key={s.id} className="ob-avatar-wrap" title={`${s.name} · last seen ${s.lastSeen || 'never'}`}>
                {s.avatar
                  ? <img src={s.avatar} className="ob-avatar offline" alt={s.name} />
                  : <div className="ob-avatar ob-avatar-letter offline" style={{ background: '#334155' }}>
                      {s.name[0]?.toUpperCase()}
                    </div>
                }
                <span className="ob-status-dot offline" />
              </div>
            ))}
          </div>
        </div>
      )}
    </div>
  )
}

function nameColor(name: string) {
  const colors = ['#16a34a','#2563eb','#9333ea','#ea580c','#0891b2','#be185d']
  let h = 0
  for (let i = 0; i < name.length; i++) h = name.charCodeAt(i) + ((h << 5) - h)
  return colors[Math.abs(h) % colors.length]
}
